### ISSUE TITLE
incorrect volume size in direct mode

### ISSUE THREAD

**Issue by krisiasty** [intel/pmem-csi#933]
I have a 5-node cluster of dual-socket machines fully populated with 512GB PMems (two regions of 6x512GB in app direct interleaved mode per node) running OpenShift 4.6.6 (kubernetes 1.19) and pmem-csi 1.9.0.

I'm requesting four 1480GiB volumes per node in direct mode, but I'm getting 1458GiB volumes instead. 
When I try to request 1500GiB volumes, I'm getting two 1482GiB volumes in one region and two 1481GiB volumes in the other one. Not only requests are not fulfilled properly, but the allocated space is also not consistent. On top of that, reported volume size is not the actual size.

The empty regions look like this:
```
[core@ocp5 ~]$ LD_LIBRARY_PATH=. ./ndctl list -RNu
[
  {
    "dev":"region1",
    "size":"3012.00 GiB (3234.11 GB)",
    "available_size":"3012.00 GiB (3234.11 GB)",
    "max_available_extent":"3012.00 GiB (3234.11 GB)",
    "type":"pmem",
    "iset_id":"0x6bcc7f481d9d2ccc",
    "persistence_domain":"memory_controller"
  },
  {
    "dev":"region0",
    "size":"3012.00 GiB (3234.11 GB)",
    "available_size":"3012.00 GiB (3234.11 GB)",
    "max_available_extent":"3012.00 GiB (3234.11 GB)",
    "type":"pmem",
    "iset_id":"0xdb067f48bfc62ccc",
    "persistence_domain":"memory_controller"
  } 
```

The PVC spec and status for 1480GiB volumes:
```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1480Gi
  storageClassName: pmem-xfs
  volumeMode: Filesystem
  volumeName: pvc-2bdecb32-1e11-4db5-913c-e08599790bbd
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1480Gi
  phase: Bound

```
The status says it's 1480Gi, but in reality its 1565515579392 bytes = 1458GiB:
```
[core@ocp5 ~]$ lsblk -b | grep pvc-2bdecb32-1e11-4db5-913c-e08599790bbd
pmem1.1                      259:5    0 1565515579392  0 disk /var/lib/kubelet/pods/b0eed186-9e21-4232-b9d5-4977b472d42d/volumes/kubernetes.io~csi/pvc-2bdecb32-1e11-4db5-913c-e08599790bbd/mount
```

And confirmation from ndctl (four volumes per node):
```
[core@ocp5 ~]$ LD_LIBRARY_PATH=. ./ndctl list -RNu
{
  "regions":[
    {
      "dev":"region1",
      "size":"3012.00 GiB (3234.11 GB)",
      "available_size":"48.00 GiB (51.54 GB)",
      "max_available_extent":"48.00 GiB (51.54 GB)",
      "type":"pmem",
      "iset_id":"0x217c7f48049b2ccc",
      "persistence_domain":"memory_controller",
      "namespaces":[
        {
          "dev":"namespace1.1",
          "mode":"fsdax",
          "map":"dev",
          "size":"1458.00 GiB (1565.52 GB)",
          "uuid":"3094b276-9dd4-11eb-9796-0a580a3c0223",
          "sector_size":512,
          "align":1073741824,
          "blockdev":"pmem1.1",
          "name":"pvc-2b-def0357682e98f9dbdc802ce26ed0106377716492ba74082a677ea7c"
        },
        {
          "dev":"namespace1.3",
          "mode":"fsdax",
          "map":"dev",
          "size":"1458.00 GiB (1565.52 GB)",
          "uuid":"23076b7c-9dd4-11eb-9796-0a580a3c0223",
          "sector_size":512,
          "align":1073741824,
          "blockdev":"pmem1.3",
          "name":"pvc-55-8a112b2edabe3a361bc2a9ffad916cd6dcee1d7440ed989b4887dc25"
        }
      ]
    },
    {
      "dev":"region0",
      "size":"3012.00 GiB (3234.11 GB)",
      "available_size":"48.00 GiB (51.54 GB)",
      "max_available_extent":"48.00 GiB (51.54 GB)",
      "type":"pmem",
      "iset_id":"0x2fc27f487d9c2ccc",
      "persistence_domain":"memory_controller",
      "namespaces":[
        {
          "dev":"namespace0.1",
          "mode":"fsdax",
          "map":"dev",
          "size":"1458.00 GiB (1565.52 GB)",
          "uuid":"4d55363e-9dd4-11eb-9796-0a580a3c0223",
          "sector_size":512,
          "align":1073741824,
          "blockdev":"pmem0.1",
          "name":"pvc-dc-506d915c45300eda3742d6b5ab21f2b262b021ed5af4d5a8f35f293d"
        },
        {
          "dev":"namespace0.3",
          "mode":"fsdax",
          "map":"dev",
          "size":"1458.00 GiB (1565.52 GB)",
          "uuid":"40e680dc-9dd4-11eb-9796-0a580a3c0223",
          "sector_size":512,
          "align":1073741824,
          "blockdev":"pmem0.3",
          "name":"pvc-36-8a2e5baf83b66756aa9f6a603df379591896de9261dbc011ae3fcdc1"
        }
      ]
    }
  ]
}

```

PmemCSIDeployment:
```
apiVersion: pmem-csi.intel.com/v1beta1
kind: PmemCSIDeployment
metadata:
  name: pmem-csi.intel.com
spec:
  deviceMode: direct
  nodeSelector:
    storage: "pmem"
```

Storege class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pmem-xfs
parameters:
  csi.storage.k8s.io/fstype: xfs
  eraseafter: "false"
provisioner: pmem-csi.intel.com
volumeBindingMode: WaitForFirstConsumer
```

Notice I had to disable 'eraseafter' since on large volumes like ~1.5TB the shred is extremely slow.
