### ISSUE TITLE
OpenShift: permissions

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#935]
It looks like privileged containers need special permissions on OpenShift. Here's an example: https://github.com/democratic-csi/charts/commit/bfdf4b174b76c191f8057fba40394122ac3ed72a

**Comment by krisiasty** [comment]
Right, I found I had to assign "privileged" security context constraint (SCC) to the *-webhooks and *-controller service accounts in the pmem-csi namespace before creating PmemCSIDeployment. You can do this manually like in the example below, but it would be much better if that could be handled automatically by the operator:
```
# oc adm policy add-scc-to-user privileged -z pmem-csi-intel-com-controller -n pmem-csi
clusterrole.rbac.authorization.k8s.io/system:openshift:scc:privileged added: "pmem-csi-intel-com-controller"

# oc  adm policy add-scc-to-user privileged -z pmem-csi-intel-com-webhooks -n pmem-csi
clusterrole.rbac.authorization.k8s.io/system:openshift:scc:privileged added: "pmem-csi-intel-com-webhooks"
```

**Comment by pohly** [comment]
Why does the webhooks service account need this? Its container doesn't need to run as privileged container.

In other words, what was failing when you didn't add that?

**Comment by krisiasty** [comment]
The webhooks service account is used by the controller pod with the following spec (fragment):
```
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: pmem-csi-intel-com-webhooks
  serviceAccountName: pmem-csi-intel-com-webhooks
```

I think the problem here is the line `runAsUser: 1000`. The UID 1000 is out of allowed UID range in the OpenShift:
```
# oc describe project pmem-csi
Name:			pmem-csi
Created:		2 weeks ago
Labels:			<none>
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"pmem-csi"}}

			openshift.io/sa.scc.mcs=s0:c24,c19
			openshift.io/sa.scc.supplemental-groups=1000590000/10000
			openshift.io/sa.scc.uid-range=1000590000/10000
```
As you can see, the uid-range is 10000 uids starting from 1000590000. To use arbitrary UID the pod needs at least **"anyuid"** SCC (or "privileged" as in the example above, but there is no need for these excessive permissions so anyuid would should be better - I did not have enough time to troubleshoot this when I first stumbled upon this problem, and cannot use existing installation for more experiments).

You can find a good overview of OpenShift UIDs here: https://www.openshift.com/blog/a-guide-to-openshift-and-uids

**Comment by pohly** [comment]
We can easily change the 1000 uid to one that gets accepted on OpenShift without a need for further privileges.

**Comment by krisiasty** [comment]
These ranges are dynamically assigned and are unique for each namespace, so you might end up with different ranges in different environments. In OpenShift, if you skip the `runAsUser` line completely, the pod should get unique uid from the correct range.

**Comment by pohly** [comment]
So if I read this correctly, OpenShift swapped the default. In upstream Kubernetes, pods run as root by default unless specified otherwise (which is why PMEM-CSI does it). In OpenShift, pods run as non-root by default, but that very same feature then prevents running pods which tried to do the right thing for upstream Kubernetes.

The simplest solution might be to not set `runAsUser` at all. We loose some security on upstream Kubernetes, but we can document how to enable it there and it might not matter in practice when no actual users run on upstream Kubernetes in production.

The remaining question then becomes whether the node pod still needs additional permissions.

**Comment by krisiasty** [comment]
You might also try to detect if the operator is running on OpenShift or use additional flag in the CRD to enable OpenShift-specific installation. 

As for the node pods, they need proper SCC in OpenShift because the pmem-driver container is run as privileged / with uid set to 0 (root). 

I'm not familiar with the pmem-csi and kubernetes code so I can only guess why you need those privileges, but if there is no other way you might try at least to limit some linux capabilities. This might be tricky because various container engines implement handles linux caps in slightly different way, so I'm not sure if it's worth it and how much effort would be needed to implement and test this properly. 
The good introductory article discussing that topic can be found here: https://www.openshift.com/blog/linux-capabilities-in-openshift

By the way, the `oc adm policy add-scc-to-user` command essentially creates the RoleBinding in specified namespace like this:
```
# oc -n pmem-csi get rolebinding system:openshift:scc:privileged -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  namespace: pmem-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: pmem-csi-intel-com-controller
  namespace: pmem-csi
- kind: ServiceAccount
  name: pmem-csi-intel-com-webhooks
  namespace: pmem-csi
```

The subjects list contains all servuce accounts or users granter with specified ClusterRole (in this case I have *-controller and *-webhooks, but the later one is not necessary if run with default uid).
